[tool.poe.tasks.add-editable-hyfi]
shell = """
  poetry remove hyfi
  poetry add --group dev --editable ../hyfi
"""
help = "Add hyfi as an editable dependency"

[tool.poe.tasks.apply-hyfi-template]
cmd = """
  copier --answers-file .copier-hyfi-config.yaml gh:entelecheia/hyfi-template .
"""
use_exec = true
help = "Apply hyfi template"

[tool.poe.tasks.copy-hyfi-config]
shell = """
  poetry add hyfi@latest
  poetry run hyfi cmd=copy_conf copier.dst_path=src/schedio/conf copier.exclude='**/*/about/__init__.yaml' copier.overwrite=True
"""
help = "Copy hyfi conf to src/schedio/conf"

[tool.poe.tasks.add-torch-source]
shell = """
  poetry source add --priority=explicit pytorch-gpu-src https://download.pytorch.org/whl/cu118
"""
help = "Add torch source"

[tool.poe.tasks.install-torch]
shell = """
  poetry add --source pytorch-gpu-src torch torchvision torchaudio
"""
help = "Install torch dependencies"
